# $NetBSD$

DISTNAME=	mccs-1.1-srcs
PKGNAME=	mccs-1.1
CATEGORIES=	misc
MASTER_SITES=	http://www.i3s.unice.fr/~cpjm/misc/
EXTRACT_SUFX=	.tgz

MAINTAINER=	vb@luminar.eu.org
HOMEPAGE=	http://www.i3s.unice.fr/~cpjm/misc/
COMMENT=	Multi Criteria CUDF Solver
LICENSE=	modified-bsd

MAKE_FILE=      makefile
USE_TOOLS+=	gmake
PKG_VERBOSE=	true

WRKSRC=	${WRKDIR}/mccs-1.1

.include "../../mk/bsd.pkg.mk"
